spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem://localhost/baseball09_db;
    username: sa
    password:
  h2:
    console:
      enabled: true
logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS,Asia/Seoul} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  level:
    org.springframework.web: error
    com.codesquad.baseball09: debug
    sql: debug


---
spring:
  profiles: prod
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://baseball-09.ckvak2aogy3v.us-east-1.rds.amazonaws.com:3306/baseball?autoReconnect=true&useSSL=false
    username: admin
    password: admin1234
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always
    hikari:
      maximum-pool-size: 10

logging:
  level:
    root: debug
    sql: trace
  pattern:
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS,Asia/Seoul} [%thread] %-5level %logger{36}.%M - %msg%n"
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS,Asia/Seoul} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  file:
    name: logs/dev_log.log
